[package]

edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
publish.workspace = true

name = "noseyparker"
version.workspace = true

[lib]
name = "noseyparker"
path = "src/lib.rs"

[features]
rule_profiling = []
libmagic = ["content_guesser/libmagic"]
gix_debug = ["gix-object/verbose-object-parsing-errors"]


[dependencies]
anyhow = { version = "1.0" }
atoi = "2.0"
bstr = { version = "1.0", features = ["serde"] }
chrono = { version = "0.4", default_features = false, features = ["std"] }
console = "0.15"
content_guesser = { path = "../content-guesser" }
fixedbitset = "0.4"

# The following two dependencies get enabled by the `gix_debug` feature
#
# note that the `verbose-object-parsing-errors` feature is:
# - broken in gix 0.53 + gix-object 0.36,
# - broken in gix 0.52 + gix-object 0.35
# - not broken in gix 0.51 + gix-object 0.33
gix = { version = "0.55", features = ["max-performance", "serde"] }
gix-object = { version = "0.38", features = ["verbose-object-parsing-errors"], optional = true }

hex = "0.4"
hyperx = "1.4"
include_dir = { version = "0.7", features = ["glob"] }
# XXX Consider switching from indicatif to status_line: https://docs.rs/status-line/latest/status_line/struct.StatusLine.html
indicatif = { version = "0.17", features = ["improved_unicode", "rayon"] }
indoc = "2.0"
ignore = "0.4"
lazy_static = "1.4"
mime = "0.3"
petgraph = "0.6"
roaring = "0.10"
regex = "1.7"
reqwest = { version = "0.11", features = ["json", "native-tls-vendored"] }
rusqlite = { version = "0.29", features = ["bundled", "backup"] }
secrecy = "0.8.0"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
smallvec = { version = "1.11", features = ["const_generics", "const_new", "union"] }
thiserror = "1"
tokio = "1.23"
tracing = "0.1"
url = "2.3"
vectorscan = { path = "../vectorscan" }

[dev-dependencies]
pretty_assertions = "1.3"
proptest = "1.0"
