name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Docker
    runs-on: ubuntu-22.04

    env:
      NP_TAG: ghcr.io/${{ github.repository }}:edge

    steps:
    - uses: actions/checkout@v4

    # The following for multi-platform build; disabled here because it takes so long; see #39.
    #
    # The docker image built for noseyparker releases is done in the
    # `release-artifacts.yml` file.
    #
    # - uses: docker/setup-qemu-action@v2

    - uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max

        context: .
        tags: ${{ env.NP_TAG }}
        push: false
        # For multi-platform builds
        # platforms: linux/amd64,linux/arm64
        load: true
        pull: true

        labels: |
          org.opencontainers.image.title=${{ github.event.repository.name }}
          org.opencontainers.image.description=${{ github.event.repository.description }}
          org.opencontainers.image.url=${{ github.event.repository.html_url }}
          org.opencontainers.image.source=${{ github.event.repository.clone_url }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.licenses=${{ github.event.repository.license.spdx_id }}

    - name: Test the Docker image
      run: docker run --rm "$NP_TAG" --version

    - name: Authenticate with GitHub Container Registry
      if: github.event_name == 'push' && github.ref_name == 'main'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push the image to `edge`
      if: github.event_name == 'push' && github.ref_name == 'main'
      run: |
        docker push "$NP_TAG"
